#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf
ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -sf $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/phpactor
ln -sf $DOTFILES/phpactor $HOME/.config/phpactor

ln -sf $DOTFILES/idea/.ideavimrc $HOME/.ideavimrc

mkdir -p $HOME/.nvm
ln -sf $DOTFILES/nvm/default-packages $HOME/.nvm/default-packages

rm -rf $HOME/.config/ghostty
ln -sf $DOTFILES/emacs/init.el $HOME/.emacs.d/init.el

rm -rf $HOME/.config/ghostty
ln -sf $DOTFILES/ghostty $HOME/.config/ghostty

rm -rf $HOME/.config/wezterm
ln -sf $DOTFILES/wezterm $HOME/.config/wezterm
